.prettierrc.yml

---
Prettier settings updated for Team Norms

Feature: Prettier settings

---

client/components/Toggle.js
client/routes.js

feat: add grid component with button toggle

---

client/components/Grid.js
client/routes.js
public/style.css

fix: route component name fix from toggle to grid

---

client/components/Grid.js
public/style.css

style: add instrumentrow component and button styling

---

.vscode/settings.json
client/store/reducers/index.js
client/store/reducers/sounds.js

feat: reset function on the redux store

---

client/components/InstrumentRow.js
package-lock.json
package.json

---
Very basic Tone.js makes a sound when a user clicks a div

Make a tone

---

client/components/Grid.js
client/store/reducers/index.js
client/store/reducers/sounds.js

---
Features: clicking Play will create a sequence and play it, clicking pause stops it, and clicking reset fully clears the sequence from tone

Play sounds

---

client/components/navbar.js

Feature: rename site title

---

README.md
server/db/models/index.js
server/db/models/loop.js

---
Created Loop model and associations, and updated the readme to include heroku link

Loop model #44

---

client/store/index.js
client/store/reducers/index.js
client/store/reducers/loops.js
client/store/reducers/sounds.js

Save loop thunk post and put

---

client/store/reducers/loops.js

fixed: destructure import

---

client/components/SaveButton.js
client/routes.js

feat: save button react component

---

client/components/UserHome.js
server/api/users.js

---
Added API route for all loops.

feat:added api get routers for all the loops #15

---

client/store/reducers/loops.js
script/seed.js

fixed: axios api route for post&put, added default title and loop seeds

---

client/components/Grid.js
client/components/InstrumentRow.js
client/components/Sequence.js
client/routes.js
client/store/reducers/sounds.js

---
Feature: Can play multiple instruments and update sequence while player is playing #71

Multiple instruments

---

client/components/UserHome.js
client/store/reducers/index.js
client/store/reducers/loops.js

---
Render saved loops on user home page.

User loops

---

client/store/reducers/index.js
client/store/reducers/loops.js

---
Added action type, action creator, thunk for create new loop.

Create new loop

---

client/components/Grid.js
client/components/SaveButton.js
client/components/Sequence.js
client/components/Tempo.js
client/routes.js
package-lock.json
package.json
public/index.html
public/style.css
server/db/models/loop.js

feat: tempo slider and extra loop columns

---

client/components/SaveButton.js
client/store/reducers/loops.js
server/api/loops.js

---
Chore: added route to update an existing loop and refactored saveButton to correctly get the loopId from the state

Chore: added route to update an existing loop

---

client/components/AudioPlayer.js
client/components/Grid.js
client/components/Sequence.js

---
Creates an audio file (ogg) on play/pause

Feature: audio component saves audio file

---

client/store/reducers/index.js
client/store/reducers/loops.js
client/store/reducers/sounds.js

---
Feature: Added isSaved state to Loops state/reducer

Feature: Added isSaved state to the Loops reducer

---

client/app.js
client/components/CreateNewLoopButton.js
client/components/SaveButton.js

Create new button

---

client/components/NotFound.js
client/routes.js

Created NotFound component, but it's not imported to routes yet
---
Feature: Custom not found component

Not found page

---

client/components/Grid.js
client/components/Sequence.js
server/index.js

---
This has 8 working sounds - export audio file is buggy with bpm slider and is exporting as ogg

Save audio file

---

client/components/UserHome.spec.js

Created test db

---

client/components/CreateNewLoopButton.js

---
Added Tone.Transport.cancel() to the button.

fixed: the create new loop works properly now

---

client/components/Sequence.js

Save audio mp4

---

client/components/CreateNewLoopButton.js
client/store/reducers/loops.js
client/store/reducers/sounds.js

Loop state

---

client/components/UserHome.js

---
Fixed bug where outdated sequence would persist if you played a loop, went to UserHome, loaded a previously saved loop, and then clicked play on /grid

Bug Fix: #119

---

client/components/SingleLoopCard.js
client/components/UserHome.js
client/store/reducers/index.js
client/store/reducers/loops.js
public/style.css
server/api/loops.js

---
Feature: Can delete a previously saved loop from UserHome

Delete loop #122

---

client/components/AuthPopup.js
client/components/LoopsInfoPopup.js
client/components/SaveButton.js
client/store/reducers/loops.js
client/store/reducers/user.js
server/api/loops.js

Popup login logout

---

client/components/Grid.js
client/components/InstrumentRow.js
client/components/Sequence.js
client/components/navbar.js
public/style.css

---
Still needs work, but new colors and nav bar font is bigger. PLEASE DO NOT DELETE

Pretty css

---

client/components/AuthPopup.js
client/components/LoopsInfoPopup.js
public/style.css

---
Style: Changed body, popup-body, and popup form css

Formatting popup

---

client/components/AudioPlayer.js
client/components/Grid.js
client/components/Sequence.js

feat:popUp for Audio Player works

---

client/components/AudioPlayer.js
public/style.css

Pop up for audio player

---

client/components/Sequence.js

---
Exports audio file as browser-friendly file

Audio file export

---

public/style.css

---
update style on logout button

Fix: Style for logout button

---

client/components/navbar.js
client/store/reducers/user.js
public/style.css

I added a tagline to the navigation as a quick way to set the context for our project. It's not styled super well, but it's a short-term solution that we can change later! 
---
Added a tagline to the nav; Reorganized CSS and added comments

Reorganize css

---

client/components/AuthPopup.js
client/components/Landing.js

---
Bug fix: AuthPopup component shows form errors and still redirects correctly #143

Popup with errors #143

---

client/components/CreateNewLoopButton.js
client/components/Landing.js
public/style.css

To grey out a button image, apply the class .disabled-button-image to the img element inside the button. To make a button unclickable and change the border colors to grey, add disabled to the button html. See Grid Button Styles in the CSS. 
---
Style: Added disabled button styles for the grid buttons/images but they're only applied to CreateNewLoopButton

Disabled button styles

---

client/components/Grid.js
client/components/Sequence.js
public/style.css

---
Fixed colors for selected sounds, reset button now cancels play, and dragon sound is quieter

Fix: muted colors, reset cancels play, dragon

---

client/components/AudioPlayer.js
client/components/Grid.js

---
Clicking export button stops play, and more user instructions to export a file

Fix: Export button stops play; user instructions

---

script/seed.js
server/db/models/loop.js

---
Updated loop model and seed file

Update loop model

---

client/components/SaveButton.js
client/components/Sequence.js
client/store/reducers/loops.js

---
Save button works better now.

Save button

---

client/components/Grid.js
client/components/Tempo.js
client/store/reducers/tempo.js

---
Fixed bpm to prevent errors with a lot of changes during play.

Chrome overload

---

client/components/SingleLoopCard.js
client/components/UserHome.js
client/routes.js
public/style.css
server/api/loops.js

---
Feature: added description to SingleLoopCards and changed the style on My Loops

My loops view

---

client/components/AudioPlayer.js
client/components/CreateNewLoopButton.js
client/components/SaveButton.js
client/store/reducers/index.js
client/store/reducers/loops.js
public/style.css

---
Fix: createNewLoop and saving button weirdness

Fix: createNewLoop and saving button weirdness #163

---

server/db/models/user.js

Model: added email validation to user model

---

server/db/models/user.js

---
Email validation for user model

Added email validation to user model

---

client/components/AuthPopup.js
package-lock.json
package.json

validation for email and password works

---

client/components/AuthPopup.js

---
Use Google to signup and login to the app

Setup o auth

---

client/components/SaveButton.js
public/style.css

---
Style: Removed excess background on authpopup and loopsinfo

Style: Removed excess background

---

client/components/AudioPlayer.js
client/components/AuthPopup.js
client/components/CreateNewLoopButton.js
client/components/Grid.js
client/components/Landing.js
client/components/LoopsInfoPopup.js
client/components/Tempo.js
client/components/UserHome.js
client/components/navbar.js
client/routes.js
client/store/reducers/sounds.js
client/store/reducers/user.js
public/style.css
script/seed.js
server/api/loops.js
server/db/models/index.js

Chore: remove logs

---

client/components/AudioPlayer.js
client/components/Grid.js
client/components/Sequence.js

---
Sounds in order high to low, export button does not start play.

Fix export and sounds

---

client/components/Grid.js

---
Reset no longer makes play button turn to pause button

Fix: reset button not trigger change in play

---

client/components/CreateNewLoopButton.js
client/components/LoopsInfoPopup.js
client/components/SaveButton.js
package-lock.json

Fixed test

---

client/store/reducers/user.spec.js

---
Test: updated thunk user test

Test: updated thunk user test

---

server/db/models/loop.spec.js

Feature: Loop model tests
